markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.hughguan.com
title: Hugh's Blog
description: Future my life with words
author: Hugh Guan
email: hughguan#gmail.com
github: hughguan

config:
  js_dir:
  img_dir:
  css_dir:
